name: Feature Request
description: Suggest new or updated features to include in pdfclown-common.
labels: ["Type: Enhancement", "Status: Triage"]
assignees:
  - stechio
type: feature
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have [searched](https://github.com/pdfclown/pdfclown-common/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/pdfclown/pdfclown-common/blob/main/docs/CONTRIBUTING.md)
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/pdfclown/.github/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Provide detailed information about the proposed feature.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Explain the benefits the new feature would bring to the use of pdfclown-common.
    validations:
      required: true