#
# On commit push or pull request events, verifies the project builds successfully, then submits its
# Dependency Snapshot (commit push only).
#
name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: pdfclown/.github/.github/workflows/build.yml@0443b2f0dffb509eace4cc5f8c592156df65007a
    permissions:
      contents: write
      security-events: write
    secrets: inherit
