#
# On commit push or pull request events, verifies the project builds successfully, then submits its
# Dependency Snapshot (commit push only).
#
name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: pdfclown/.github/.github/workflows/build.yml@edf09a273a7e408850468143be99c6009cd0461e
    permissions:
      contents: write
      security-events: write
    secrets: inherit
