#
# On commit push or pull request events, verifies the project builds successfully, then submits its
# Dependency Snapshot (commit push only).
#
name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    uses: pdfclown/.github/.github/workflows/build.yml@b04b5e473b6bce73799d816546863412d99fbd1f
    permissions:
      contents: write
      security-events: write
    secrets: inherit
