#
# On pull request events, verifies the PR conforms to project conventions.
#
name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  main:
    uses: pdfclown/.github/.github/workflows/pull-request.yml@5f6a086ad568b33303206bfca6d746d3f9015e74
    permissions:
      pull-requests: read
    secrets: inherit
