#
# On pull request events, verifies the PR conforms to project conventions.
#
name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited

jobs:
  main:
    uses: pdfclown/.github/.github/workflows/pull-request.yml@13af571d3e068b7616aa250717425665c236f90e
    permissions:
      pull-requests: read
    secrets: inherit
